# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: webapp-depl
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       app: webapp
#   template:
#     metadata:
#       labels:
#         app: webapp
#     spec:
#       containers:
#       - name: webapp
#         image: shamikatissera/banking-webapp:latest
#         ports:
#         - containerPort: 3000

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: webapp-srv
# spec:
#   type: NodePort
#   selector:
#     app: webapp
#   ports:
#     - protocol: TCP
#       port: 3000
#       targetPort: 3000
